# Generated by Django 3.1.3 on 2020-12-09 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DangerLevel',
            fields=[
                ('danger_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('water_level', models.DecimalField(decimal_places=12, max_digits=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='River',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('river_name', models.CharField(max_length=200, null=True)),
                ('river_location', models.CharField(max_length=200, null=True)),
                ('river_trend', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarningLevel',
            fields=[
                ('warning_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('river', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.river')),
            ],
        ),
        migrations.CreateModel(
            name='WaterLevelStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterLevel',
            fields=[
                ('level_id', models.AutoField(primary_key=True, serialize=False)),
                ('water_level', models.FloatField()),
                ('date_time', models.DateTimeField()),
                ('danger_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.dangerlevel')),
                ('rid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.river')),
                ('status_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.waterlevelstatus')),
                ('warning_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.warninglevel')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=200, null=True)),
                ('station_location', models.CharField(max_length=200, null=True)),
                ('river', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.river')),
            ],
        ),
        migrations.AddField(
            model_name='dangerlevel',
            name='rid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.river'),
        ),
    ]
