# Generated by Django 2.2.14 on 2020-12-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarningDataset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='WarningMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('river_trend', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='date',
            new_name='date_time',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='image',
        ),
    ]
