# Generated by Django 2.2.14 on 2021-01-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_dataset_delay_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='delay_time',
            field=models.DateField(),
        ),
    ]
