# Generated by Django 2.2.14 on 2021-01-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_dataset_delay_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='delay_time',
            field=models.IntegerField(),
        ),
    ]
