# Generated by Django 3.1.6 on 2021-02-23 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('stationID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WarningMessageData',
            fields=[
                ('warningID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('threshold', models.CharField(max_length=10)),
                ('season', models.CharField(max_length=15)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WarningMessage',
            fields=[
                ('messageID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='webapp.station')),
                ('warningValue', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='webapp.warningmessagedata')),
            ],
        ),
        migrations.CreateModel(
            name='DrainageTrend',
            fields=[
                ('trendID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('trendValue', models.DecimalField(decimal_places=3, max_digits=10)),
                ('dateTime', models.DateTimeField()),
                ('station', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='webapp.station')),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('drainageLevel', models.DecimalField(decimal_places=3, max_digits=10)),
                ('delayTime', models.DecimalField(decimal_places=3, max_digits=10)),
                ('station', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='webapp.station')),
            ],
        ),
        migrations.CreateModel(
            name='Average',
            fields=[
                ('averageID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('oneHour', models.DecimalField(decimal_places=3, max_digits=10)),
                ('threeHour', models.DecimalField(decimal_places=3, max_digits=10)),
                ('sixHour', models.DecimalField(decimal_places=3, max_digits=10)),
                ('nineHour', models.DecimalField(decimal_places=3, max_digits=10)),
                ('twelveHour', models.DecimalField(decimal_places=3, max_digits=10)),
                ('oneDay', models.DecimalField(decimal_places=3, max_digits=10)),
                ('oneWeek', models.DecimalField(decimal_places=3, max_digits=10)),
                ('twoWeek', models.DecimalField(decimal_places=3, max_digits=10)),
                ('threeWeek', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fourWeek', models.DecimalField(decimal_places=3, max_digits=10)),
                ('dateTime', models.DateTimeField()),
                ('station', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='webapp.station')),
            ],
        ),
    ]
