# Generated by Django 3.1.6 on 2021-02-02 10:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='average',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 2, 2, 10, 11, 40, 660700, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
