# Generated by Django 3.1.6 on 2021-02-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DrainageTrend',
        ),
    ]
