# Generated by Django 3.1.6 on 2021-02-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_drainagetrend'),
    ]

    operations = [
        migrations.AddField(
            model_name='drainagetrend',
            name='yIntercept',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
