# Generated by Django 3.1.6 on 2021-02-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_drainagetrend_yintercept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='average',
            name='averageID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
