# Generated by Django 3.1.6 on 2021-02-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20210223_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='average',
            name='averageID',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='drainagetrend',
            name='trendID',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
