# Generated by Django 3.1.6 on 2021-02-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20210223_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='average',
            name='fourWeek',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='station',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='station',
            name='stationID',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
