# Generated by Django 3.1.6 on 2021-02-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20210223_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='average',
            name='nineHour',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='average',
            name='oneDay',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='average',
            name='oneHour',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='average',
            name='oneWeek',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='average',
            name='sixHour',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='average',
            name='threeHour',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='average',
            name='threeWeek',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='average',
            name='twelveHour',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='average',
            name='twoWeek',
            field=models.DateTimeField(),
        ),
    ]
