# Generated by Django 3.1.6 on 2021-02-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20210224_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='average',
            name='averageID',
        ),
        migrations.AddField(
            model_name='average',
            name='id',
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
