# Generated by Django 3.1.6 on 2021-02-25 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20210224_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='station',
            field=models.ForeignKey(default='S1', on_delete=django.db.models.deletion.SET_DEFAULT, to='webapp.station'),
        ),
    ]
