# Generated by Django 3.1.6 on 2021-02-25 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20210225_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
