# Generated by Django 3.1.6 on 2021-02-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20210225_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='average',
            name='fourWeek',
            field=models.DecimalField(decimal_places=3, max_digits=100),
        ),
        migrations.AlterField(
            model_name='average',
            name='nineHour',
            field=models.DecimalField(decimal_places=3, max_digits=100),
        ),
        migrations.AlterField(
            model_name='average',
            name='oneDay',
            field=models.DecimalField(decimal_places=3, max_digits=100),
        ),
        migrations.AlterField(
            model_name='average',
            name='oneHour',
            field=models.DecimalField(decimal_places=3, max_digits=100),
        ),
        migrations.AlterField(
            model_name='average',
            name='oneWeek',
            field=models.DecimalField(decimal_places=3, max_digits=100),
        ),
        migrations.AlterField(
            model_name='average',
            name='sixHour',
            field=models.DecimalField(decimal_places=3, max_digits=100),
        ),
        migrations.AlterField(
            model_name='average',
            name='threeHour',
            field=models.DecimalField(decimal_places=3, max_digits=100),
        ),
        migrations.AlterField(
            model_name='average',
            name='threeWeek',
            field=models.DecimalField(decimal_places=3, max_digits=100),
        ),
        migrations.AlterField(
            model_name='average',
            name='twelveHour',
            field=models.DecimalField(decimal_places=3, max_digits=100),
        ),
        migrations.AlterField(
            model_name='average',
            name='twoWeek',
            field=models.DecimalField(decimal_places=3, max_digits=100),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='delayTime',
            field=models.DecimalField(decimal_places=3, max_digits=100),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='drainageLevel',
            field=models.DecimalField(decimal_places=3, max_digits=100),
        ),
        migrations.AlterField(
            model_name='drainagetrend',
            name='trendValue',
            field=models.DecimalField(decimal_places=3, max_digits=100),
        ),
        migrations.AlterField(
            model_name='drainagetrend',
            name='yIntercept',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=100),
        ),
    ]
