# Generated by Django 3.1.6 on 2021-06-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20210225_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='communityHero1',
            field=models.CharField(default='John Doe, 980XXXXXX', max_length=255),
        ),
        migrations.AddField(
            model_name='station',
            name='communityHero2',
            field=models.CharField(default='John Doe, 980XXXXXX', max_length=255),
        ),
    ]
