# Generated by Django 3.1.6 on 2021-06-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_station_mapimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='mapImage',
            field=models.ImageField(blank=True, null=True, upload_to='assets/stationimg/'),
        ),
    ]
