# Generated by Django 3.1.6 on 2021-06-13 16:51

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20210613_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='communityHero1Image',
            field=models.ImageField(blank=True, null=True, upload_to=webapp.models.image_community1),
        ),
        migrations.AddField(
            model_name='station',
            name='communityHero2Image',
            field=models.ImageField(blank=True, null=True, upload_to=webapp.models.image_community2),
        ),
    ]
