# Generated by Django 3.1.6 on 2021-07-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20210613_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='dangerLevel',
            field=models.DecimalField(decimal_places=1, default=3.0, max_digits=100),
        ),
        migrations.AddField(
            model_name='station',
            name='warningLevel',
            field=models.DecimalField(decimal_places=1, default=0.5, max_digits=100),
        ),
    ]
