# Generated by Django 3.1.6 on 2021-07-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_auto_20210705_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='EmergencyNumbers',
            field=models.CharField(default='1234567', max_length=255),
        ),
        migrations.AddField(
            model_name='station',
            name='EmergencyNumbersTitle',
            field=models.CharField(default='test', max_length=255),
        ),
    ]
