# Generated by Django 3.1.6 on 2021-07-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_auto_20210706_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='GlobalNames',
            field=models.TextField(default='नेपाल प्रहरी,जिल्ला आपतकालीन कार्य संचालन केन्द्र,महाकाली बेसिन फिल्ड कार्यालय अत्तरिया,सशस्त्र प्रहरी वल नेपाल नं. ३५ गण'),
        ),
        migrations.AddField(
            model_name='station',
            name='GlobalNumbers',
            field=models.TextField(default='१००,०९९-५२५२४५,०९१-५५०६२२,०९९-५४०१३३'),
        ),
    ]
